name = "mc.zba.su pack"
author = "zaboal, merededdo"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4c645cc4b4657dbb6fa8c0eedd1b582e4dd847cdbde142ed35884fe722582a1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
