name = "mc.zba.su pack"
author = "zaboal, merededdo"
version = "0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7c065d874b532268ffed07fd4ed7afbc5b5e102f53cb1b6a4f12ddd11adc941"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
