name: Export modpack as artifact

on: push

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install packwiz
        run: curl -L -o packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip && unzip -d /tmp/ packwiz.zip && mkdir -p $HOME/.local/bin/ && mv /tmp/packwiz $HOME/.local/bin/packwiz && chmod +x $HOME/.local/bin/packwiz && rm packwiz.zip
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Export modpack
        run: bash -c '$HOME/.local/bin/packwiz modrinth export --output "mc.zba.su pack.mrpack"'
      - name: Upload mcpack
        uses: actions/upload-artifact@v4
        with:
          name: mrpack
          path: 'mc.zba.su pack.mrpack'
