name: Export modpack as artifact

on: 
  push:
    paths:
      - packwiz

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install packwiz
        run: curl -L -o /tmp/packwiz.zip https://nightly.link/packwiz/packwiz/workflows/go/main/Linux%2064-bit%20x86.zip && mkdir -p $HOME/.local/bin/ && unzip -d $HOME/.local/bin/ /tmp/packwiz.zip && chmod +x $HOME/.local/bin/packwiz && rm /tmp/packwiz.zip
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Export modpack
        run: |
          cd packwiz
          bash -c '$HOME/.local/bin/packwiz modrinth export --output "mc.zba.su pack.mrpack"'
      - name: Upload mcpack
        uses: actions/upload-artifact@v4
        with:
          name: mrpack
          path: 'mc.zba.su pack.mrpack'
